name: Test and coverage

on: [push, pull_request]

env:
  PACKAGES: io

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
          - 1.20
          - stable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run test
        run: |
          WORKDIR=$PWD 
          for p in $(echo $PACKAGES | sed "s/,/ /g") 
          do 
            cd "$WORKDIR/$p"
            go test ./... -race -covermode=atomic
          done
          cd $WORKDIR
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Run coverage
        run: |
          COVERAGE=
          WORKDIR=$PWD 
          for p in $(echo $PACKAGES | sed "s/,/ /g") 
          do 
            cd "$WORKDIR/$p"
            go test ./... -race -coverprofile=coverage.out -covermode=atomic
            COVERAGE+="./$p/coverage.out,"
          done
          cd $WORKDIR
          COVERAGE=${COVERAGE%,}
          echo $COVERAGE
          echo "COVERAGE=$COVERAGE" >> "$GITHUB_ENV"
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ${{ env.COVERAGE }}
          verbose: true